sudo: false
language: node_js
cache: yarn
node_js:
  - '9'
  - '8'
  - '6'
script:
  - yarn test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: 'yarn install && yarn build && npx semantic-release'
        on:
          branch: master
